<?php 
$produtos = array(
   array("nome" => "Produto 01", "valor" => "15.00", "desconto" => "20.00", "image" => "images/product-1.jpg", "descricao" => "it has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages" ),
   array("nome" => "Produto 02", "valor" => "13.00", "desconto" => "17.00", "image" => "images/product-2.jpg" , "descricao" => "lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."),
   array("nome" => "Produto 03", "valor" => "12.00", "desconto" => "15.00", "image" => "images/product-3.jpg" , "descricao" => "Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc."),
   array("nome" => "Produto 04", "valor" => "12.00", "desconto" => "15.00", "image" => "images/product-4.jpg" , "descricao" => "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text."),
   array("nome" => "Produto 05", "valor" => "12.00", "desconto" => "15.00", "image" => "images/product-5.jpg", "descricao" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old."),
   array("nome" => "Produto 06", "valor" => "12.00", "desconto" => "15.00", "image" => "images/product-6.jpg", "descricao" => "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham."),
   array("nome" => "Produto 07", "valor" => "10.00", "desconto" => "12.00", "image" => "images/product-7.jpg", "descricao" => "Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."),
   array("nome" => "Produto 08", "valor" => "10.00", "desconto" => "12.00", "image" => "images/product-8.jpg", "descricao" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "),
);
?>